-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 18:59:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_lenderV3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_lenderV3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_lenderV3` ;
USE `db_lenderV3` ;

-- -----------------------------------------------------
-- Table `db_lenderV3`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lenderV3`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `db_lenderV3`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rol` ENUM('admin', 'cliente') NOT NULL,
  `estado` ENUM('ACTIVO', 'NO_ACTIVO') NULL DEFAULT 'ACTIVO',
  `privilegio` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX (`num_documento` ASC) VISIBLE,
  UNIQUE INDEX (`email` ASC) VISIBLE,
  UNIQUE INDEX (`usuario` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `db_lenderV3`.`perfil_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lenderV3`.`perfil_cliente` ;

CREATE TABLE IF NOT EXISTS `db_lenderV3`.`perfil_cliente` (
  `id_perfil_cliente` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `entidad_bancaria` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_cuenta` ENUM('Ahorros', 'Corriente') NOT NULL,
  `numero_cuenta` VARCHAR(50) NOT NULL,
  `num_documento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_perfil_cliente`),
  UNIQUE INDEX (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX (`numero_cuenta` ASC) VISIBLE,
  UNIQUE INDEX (`num_documento` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_lenderV3`.`usuarios` (`id_usuarios`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `db_lenderV3`.`prestamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lenderV3`.`prestamos` ;

CREATE TABLE IF NOT EXISTS `db_lenderV3`.`prestamos` (
  `id_prestamo` INT NOT NULL AUTO_INCREMENT,
  `prestamo_codigo` VARCHAR(20) NOT NULL,
  `tasa_interes` DECIMAL(5,2) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `plazo_meses` INT NOT NULL,
  `estado` ENUM('ACTIVO', 'PAGADO', 'VENCIDO') NOT NULL,
  `monto_prestamo` DECIMAL(12,2) NOT NULL,
  `monto_intereses` DECIMAL(12,2) NOT NULL,
  `total` DECIMAL(12,2) NOT NULL,
  `pagado` DECIMAL(12,2) NULL DEFAULT 0,
  `saldo_pendiente` DECIMAL(12,2) NOT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id_prestamo`),
  UNIQUE INDEX (`prestamo_codigo` ASC) VISIBLE,
  INDEX (`cliente_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_lenderV3`.`perfil_cliente` (`id_perfil_cliente`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `db_lenderV3`.`transacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lenderV3`.`transacciones` ;

CREATE TABLE IF NOT EXISTS `db_lenderV3`.`transacciones` (
  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
  `monto` DECIMAL(12,2) NOT NULL,
  `fecha_transaccion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo_transaccion` ENUM('INCREMENTO', 'ABONO_CAPITAL', 'INTERES', 'ABONO_INTERESES') NOT NULL,
  `prestamo_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX (`prestamo_id` ASC) VISIBLE,
  INDEX (`usuario_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`prestamo_id`)
    REFERENCES `db_lenderV3`.`prestamos` (`id_prestamo`)
    ON DELETE CASCADE,
  CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_lenderV3`.`usuarios` (`id_usuarios`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `db_lenderV3`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_lenderV3`.`empresa` ;

CREATE TABLE IF NOT EXISTS `db_lenderV3`.`empresa` (
  `id_empresa` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX (`email` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
